name: CMake Build
run-name: CMake Build
on: [push, pull_request]
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          tag_prefix: 'tags'
      - name: Use version
        run:
          echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodule update
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: sudo apt-get install libgl1-mesa-dev
    - name: Set up CMake
      uses: threeal/cmake-action@v1.3.0
      with:
        cmake-version: '3.17.0'
    - name: Build
      run: cmake -B build && cmake --build build --config Debug -j 4
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
