name: CMake Build
run-name: CMake Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: threeal/cmake-action@v1.3.0
      with:
        cmake-version: '3.17.0'
    - name: Build
      run: cmake -B build && cmake --build build --config Debug -j 4
